# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = [
  "knative.dev/pkg/codegen/cmd/injection-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",

  # temporary until route code is actually used
  "github.com/openshift/client-go/route/clientset/versioned",
  "github.com/openshift/client-go/route/informers/externalversions",
  "github.com/openshift/api/route/v1",

  # temporary until servicemesh code is actually used
  "github.com/maistra/istio-operator/pkg/apis"
]

[[override]]
  name = "knative.dev/serving"
  branch = "master"

[[override]]
  name = "github.com/openshift/client-go"
  branch = "master"

[[override]]
  name = "github.com/Maistra/istio-operator"
  branch = "maistra-1.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "knative.dev/pkg"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false